In [1]:
import multiprocessing
import jieba
import jieba.analyse
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import Word2Vec
from gensim.models import KeyedVectors
from gensim.models import word2vec

# import logging
import os

In [ ]:
sentences = word2vec.LineSentence('Tencent_news_Result.txt')
path = get_tmpfile("w2v_model.bin") #创建临时文件
cbmodel = Word2Vec(sentences, size=100, window=5, min_count=1, iter=10 ,workers=multiprocessing.cpu_count())

D:\anaconda3\lib\site-packages\gensim\models\base_any2vec.py:743: UserWarning: C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.
  "C extension not loaded, training will be slow. "


In [8]:
model.wv.save_word2vec_format('cbgonganmodel.bin',binary = True)

In [68]:
for key in cbmodel.similar_by_word('爆炸', topn =10):
    print(key)

('极易', 0.9935521483421326)
('困难', 0.9934874773025513)
('过路', 0.9931451082229614)
('车辆通行', 0.9927283525466919)
('无法', 0.9927146434783936)
('太', 0.9925479888916016)
('信号灯', 0.9923542141914368)
('同时', 0.992228090763092)
('及', 0.9920909404754639)
('受到', 0.9918867349624634)


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `similar_by_word` (Method will be removed in 4.0.0, use self.wv.similar_by_word() instead).
  """Entry point for launching an IPython kernel.


In [69]:
cbmodel["爆炸"]

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.00844468, -0.01960895,  0.01672795, -0.0261167 ,  0.00509361,
       -0.02561911,  0.01675329,  0.0038734 ,  0.04909154,  0.00857049,
        0.07442446, -0.1116773 ,  0.04822423, -0.0556086 , -0.00657536,
        0.03657444, -0.05326466,  0.01157148, -0.01422363,  0.00541145,
        0.00346457,  0.02509604, -0.0187537 ,  0.02655778, -0.02183228,
        0.05193711, -0.08002175, -0.01257197, -0.02308513,  0.00139855,
        0.0482249 , -0.00153102, -0.01204232, -0.08629581,  0.0248101 ,
       -0.01722659, -0.04806007, -0.0023226 ,  0.04780351,  0.00366191,
        0.00460518,  0.01596103,  0.02035832, -0.0822442 , -0.02424444,
        0.00134193,  0.06490051, -0.04053535, -0.0225993 ,  0.01513438,
        0.00410855, -0.04871228,  0.02484216,  0.02018281, -0.05631958,
        0.04296947,  0.05393486, -0.02370854, -0.00843136,  0.0137609 ,
        0.01090148, -0.02636641, -0.03545165,  0.04489356, -0.00677312,
       -0.01805393,  0.01714433, -0.05667847, -0.0302602 ,  0.01

In [70]:
import pandas as pd
import jieba
def chinese_word_cut(mytext):
    return " ".join(jieba.cut(mytext))
df = pd.read_csv('wenben.csv')
X = df[['xinxi']]
X['cutted_xinxi'] = X.xinxi.apply(chinese_word_cut)




Y = open('1.1.txt',encoding = 'UTF-8-sig').read().split('\n')


In [71]:
X.shape

(1461, 2)

In [72]:
X=X[["cutted_xinxi"]]
X.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)

In [73]:
from sklearn.naive_bayes import MultinomialNB 
from sklearn.preprocessing import scale
from sklearn.naive_bayes import GaussianNB
import numpy as np
import gensim
VECTOR_DIR = 'vectors.bin'

MAX_SEQUENCE_LENGTH = 100
EMBEDDING_DIM = 128
TEST_SPLIT = 0.2
CBmodel2 = gensim.models.KeyedVectors.load_word2vec_format(VECTOR_DIR, binary=True)


In [74]:
def buildWordVector(text, size):
    '''
        利用函数获得每个文本中所有词向量的平均值来表征该特征向量。
    '''
    vec = np.zeros(100).reshape((1, size))
    count = 0
    for word in text:
        try:
            vec += cbmodel[word].reshape((1, 100))
            count += 1
        except KeyError:
            continue
    if count != 0:
        vec /= count
    return vec
    
'''获取需要所有文档的词向量，并且标准化出来'''
x_train1 = np.concatenate([buildWordVector(x, 100) for x in X_train.cutted_xinxi])
print ("the shape of train is "+repr(x_train1.shape) ) 
x_train = scale(x_train1)
x_test1 = np.concatenate([buildWordVector(x, 100) for x in X_test.cutted_xinxi])
print ("the shape of train is "+repr(x_test1.shape) ) 
x_test = scale(x_test1)

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


the shape of train is (1095, 100)
the shape of train is (366, 100)


In [75]:
x_train

array([[-0.93481705, -1.27952796,  1.21519861, ...,  0.31532867,
        -2.0523159 ,  1.27775492],
       [-0.03026029,  2.49586811, -2.42984166, ...,  1.28701296,
         1.1127782 , -0.9396904 ],
       [ 0.68406502, -1.10243218,  1.07443682, ..., -0.72182135,
        -0.98560868, -0.02987566],
       ..., 
       [-0.84487802,  1.5978637 , -1.49684738, ...,  1.52852354,
         0.30026652, -0.03844758],
       [ 0.05666303,  0.58060373, -0.54487036, ..., -0.71117582,
         1.08112828, -0.03369656],
       [-0.35405733, -0.71637541,  0.94388109, ..., -0.58223909,
        -1.10551235,  0.8197568 ]])

In [76]:
clf = GaussianNB()  
clf.fit(x_train, y_train);  
preds = clf.predict(x_test);
num = 0
preds = preds.tolist()
for i,pred in enumerate(preds):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(preds)))

precision_score:0.6120218579234973


In [77]:
from sklearn.svm import SVC   
svclf = SVC(kernel = 'linear') 
svclf.fit(x_train,y_train)  
predss = svclf.predict(x_test);  
num = 0
predss = predss.tolist()
for i,pred in enumerate(predss):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(preds)))

precision_score:0.8879781420765027


In [78]:
from sklearn.neighbors import KNeighborsClassifier 
clf = KNeighborsClassifier()  
clf.fit(x_train, y_train);  
predsss = clf.predict(x_test);
num = 0
predsss = predsss.tolist()
for i,pred in enumerate(predsss):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(preds)))

precision_score:0.8770491803278688


In [79]:
from sklearn import metrics
metrics.confusion_matrix(y_test, predsss)

array([[320,   4],
       [ 41,   1]], dtype=int64)

In [80]:
print(metrics.f1_score(y_test,predsss,labels=[1,0],average='micro'))

0.877049180328


D:\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:459: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)


In [81]:
print(metrics.f1_score(y_test,predsss,labels=[1,0],average='macro'))

0.488429880416


D:\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:459: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
