In [1]:
import multiprocessing
import jieba
import jieba.analyse
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import Word2Vec
from gensim.models import KeyedVectors
from gensim.models import word2vec

# import logging
import os

In [18]:
sentences = word2vec.LineSentence('data3.txt')
path = get_tmpfile("w2v_model2.bin") #创建临时文件
spmodel = Word2Vec(sentences, size=100, window=10,sg=1, min_count=1,workers=multiprocessing.cpu_count())

D:\anaconda3\lib\site-packages\gensim\models\base_any2vec.py:743: UserWarning: C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.
  "C extension not loaded, training will be slow. "


In [ ]:
model.wv.save_word2vec_format('cbgonganmodel.bin',binary = True)

In [3]:
for key in spmodel.similar_by_word('爆炸', topn =10):
    print(key)

('怨声载道', 0.9837099313735962)
('美好', 0.9834924340248108)
('真心', 0.9834119081497192)
('生命财产', 0.9821381568908691)
('严加', 0.9808769822120667)
('传染病', 0.9805291295051575)
('易有', 0.980425238609314)
('生命安全', 0.9798831939697266)
('劝说', 0.9785289764404297)
('求', 0.9779046773910522)


D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `similar_by_word` (Method will be removed in 4.0.0, use self.wv.similar_by_word() instead).
  """Entry point for launching an IPython kernel.


In [4]:
spmodel["爆炸"]

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.27665943, -0.3183454 ,  0.37644538,  0.1313346 , -0.12299901,
        0.13735959, -0.0904852 ,  0.1483036 ,  0.23479797, -0.0380918 ,
        0.162834  ,  0.1529374 ,  0.10948602,  0.1225908 ,  0.14507079,
        0.23567413,  0.26785523, -0.07244071, -0.41427478,  0.03704834,
       -0.11803831, -0.0989292 ,  0.08342316,  0.02250017, -0.03648548,
        0.08160986, -0.0076189 ,  0.02600959,  0.21826741,  0.03566729,
       -0.16359176,  0.0339879 , -0.26034451,  0.15123361,  0.27822307,
        0.13392808,  0.07012361, -0.44978499, -0.09577505,  0.07963108,
       -0.21628796,  0.00463233, -0.10124639, -0.1191857 ,  0.21636309,
        0.12522632, -0.17867105, -0.34192839, -0.02541428,  0.47974166,
       -0.14490943, -0.28721717,  0.04146675,  0.15614368, -0.32490167,
        0.10309174,  0.28783923, -0.129095  , -0.15074062,  0.08483274,
        0.13096677,  0.24493404, -0.02492385,  0.15508035, -0.07268898,
       -0.05231657,  0.27173433,  0.0274427 , -0.11129036, -0.22

In [5]:
import pandas as pd
import jieba
def chinese_word_cut(mytext):
    return " ".join(jieba.cut(mytext))
df = pd.read_csv('wenben.csv')
X = df[['xinxi']]
X['cutted_xinxi'] = X.xinxi.apply(chinese_word_cut)


Y = open('1.1.txt',encoding = 'UTF-8-sig').read().split('\n')


Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\mazheng\AppData\Local\Temp\jieba.cache
Loading model cost 0.763 seconds.
Prefix dict has been built succesfully.


In [6]:
X=X[["cutted_xinxi"]]
X.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)

In [7]:
from sklearn.naive_bayes import MultinomialNB 
from sklearn.preprocessing import scale
from sklearn.naive_bayes import GaussianNB
import numpy as np

MAX_SEQUENCE_LENGTH = 100
EMBEDDING_DIM = 128
TEST_SPLIT = 0.2


In [8]:
def buildWordVector(text, size):
    '''
        利用函数获得每个文本中所有词向量的平均值来表征该特征向量。
    '''
    vec = np.zeros(100).reshape((1, size))
    count = 0
    for word in text:
        try:
            vec += spmodel[word].reshape((1, 100))
            count += 1
        except KeyError:
            continue
    if count != 0:
        vec /= count
    return vec
    
'''获取需要所有文档的词向量，并且标准化出来'''
x_train1 = np.concatenate([buildWordVector(x, 100) for x in X_train.cutted_xinxi])
print ("the shape of train is "+repr(x_train1.shape) ) 
x_train = scale(x_train1)
x_test1 = np.concatenate([buildWordVector(x, 100) for x in X_test.cutted_xinxi])
print ("the shape of train is "+repr(x_test1.shape) ) 
x_test = scale(x_test1)

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  if __name__ == '__main__':


the shape of train is (1095, 100)
the shape of train is (366, 100)


In [9]:
x_train

array([[-0.69395982, -0.03021795,  0.54635503, ..., -0.03393326,
         0.31121575, -1.3627295 ],
       [ 1.27435321,  0.12839862,  0.26471933, ..., -1.31025565,
        -0.03908937,  0.46256896],
       [ 0.13808423, -0.25770024, -0.27594626, ..., -1.09128773,
        -1.49541627, -1.19335468],
       ..., 
       [ 0.98337782, -0.20110153,  0.24454054, ..., -1.08463818,
        -1.15794769,  0.72350641],
       [ 1.09426075,  0.60606594,  1.98410402, ..., -1.65209673,
        -0.46286146,  0.95782314],
       [ 0.74079144,  0.49867351, -0.9844574 , ...,  0.45899866,
         0.15928014, -0.91666438]])

In [10]:
clf = GaussianNB()  
clf.fit(x_train, y_train);  
preds = clf.predict(x_test);
num = 0
preds = preds.tolist()
for i,pred in enumerate(preds):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(preds)))

precision_score:0.7786885245901639


In [11]:
from sklearn.svm import SVC   
svclf = SVC(kernel = 'linear') 
svclf.fit(x_train,y_train)  
predss = svclf.predict(x_test);  
num = 0
predss = predss.tolist()
for i,pred in enumerate(predss):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(predss)))

precision_score:0.8852459016393442


In [12]:
from sklearn.neighbors import KNeighborsClassifier 
clf = KNeighborsClassifier()  
clf.fit(x_train, y_train);  
preds = clf.predict(x_test);
num = 0
preds = preds.tolist()
for i,pred in enumerate(preds):
    if int(pred) == int(y_test[i]):
        num += 1
print ('precision_score:' + str(float(num) / len(preds)))

precision_score:0.8743169398907104


In [13]:
from sklearn import metrics
metrics.confusion_matrix(y_test, predss)

array([[324,   0],
       [ 42,   0]], dtype=int64)

In [14]:
P=324/366
Z=324/(324+41)

In [15]:
P

0.8852459016393442

In [16]:
Z

0.8876712328767123

In [17]:
(2*P*Z)/(P+Z)

0.8864569083447333